server:
  port: 8021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.pradipta.organization
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: 127.0.0.1 
      port: 27017
      database: organizationdb         
      
management:
  endpoints:
    web:
      exposure:
        include: '*'      
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true    

feign:
    hystrix:
        enabled: true      