server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: mongodb 
      port: 27017
      database: employeedb
            
      
management:
  endpoints:
    web:
      exposure:
        include: '*'      